export const INSPECTION_STATUS = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  FIRST_REVIEW: 'FIRST_REVIEW',
  SECOND_REVIEW: 'SECOND_REVIEW',
  COMPLETED: 'COMPLETED',
  PUBLISHED: 'PUBLISHED',
  CANCELLED: 'CANCELLED',
} as const;

export const INSPECTION_TYPE = {
  CONDITION: 'CONDITION',
  ROUTINE: 'ROUTINE',
  INGOING: 'INGOING',
  OUTGOING: 'OUTGOING',
  WARD_ROUND: 'WARD_ROUND',
  OPEN: 'OPEN',
} as const;

export const POOL_INSPECTION_TYPES = [
  INSPECTION_TYPE.OPEN,
  INSPECTION_TYPE.ROUTINE,
  INSPECTION_TYPE.INGOING,
  INSPECTION_TYPE.OUTGOING,
] as const;

export const OUTSTANDING_STATUSES = [
  INSPECTION_STATUS.DRAFT,
  INSPECTION_STATUS.IN_PROGRESS,
] as const;

export const BILLING_SOURCE = {
  ROUTINE_INSPECTION: 'ROUTINE_INSPECTION',
  TRIBUNAL: 'TRIBUNAL',
} as const;

export const INVOICE_STATUS = {
  PENDING: 'PENDING',
  INVOICED: 'INVOICED',
  PAID: 'PAID',
} as const;
